<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <RootNamespace>DarkUI</RootNamespace>
    <AssemblyName>DarkUI</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Resources\**\*">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Icons\*.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>%(Filename).Designer.cs</LastGenOutput>
      <CustomToolNamespace>DarkUI.Icons</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Icons\MenuIcons.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <Compile Update="Icons\*.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>%(Filename).resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Icons\Resource1.Designer.cs">
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
